# FUNDING.yml
# Gene De Lisa
# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

# github: genedelisa
custom: ["https://www.paypal.me/genedelisa"]

